### ISSUE TITLE
RLE decomp doesn't work

### ISSUE THREAD

**Issue by applecuckoo** [Tiniifan/Level-5-blender-addon#4]
Hi! I was trying to rip rig c002008 and errored out to `IndexError: index out of range`. I ended up ripped the model using Metanoia to do a bit of investigation. In Blender it seems that the watch from the 'bad rig' is higher poly than the ones from other rigs that imported on first try. My thinking is that this might be a weird new 'high quality' mode? Here's a screenshot (ignore the shading problems, that seems to be a Metanoia vs. plugin thing)
![highpolywatch](https://github.com/Tiniifan/Level-5-blender-addon/assets/113647417/8e1f9fd3-dc1a-48eb-9de0-a8a5105bd0b4)

**Comment by Tiniifan** [comment]
Hi, the problem isn't the polys, all polys are triangles and the addon can read models with lots of triangles like maps.
Most of the time, if your model can't be opened and you get an ``IndexError: index out of range error``, it's because the [RLE decompression from the addon](https://github.com/Tiniifan/Level-5-blender-addon/blob/main/compression/rle.py) is bad and needs to be fixed.
